version = 0.1  

[default]  
stack_name = "child-health-data-platform"  
s3_bucket = "child-health-data-bucket"  # Replace with your actual bucket name  
# s3_prefix = "your-s3-prefix"        # Optional, set if needed  
region = "us-east-1"  
confirm_changeset = true  
capabilities = "CAPABILITY_IAM"
