AWSTemplateFormatVersion: '2010-09-09'  
Transform: AWS::Serverless-2016-10-31  
Description: MVP for Global Child Health Project  

Resources:  

  ApiGateway:  
    Type: AWS::Serverless::Api  
    Properties:  
      StageName: Prod  
      Cors:  
        AllowMethods: "'GET,POST,OPTIONS'"  
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"  
        AllowOrigin: "'*'"  

  IngestFunction:  
    Type: AWS::Serverless::Function  
    Properties:  
      Handler: app.ingest_data  
      Runtime: python3.8  
      Events:  
        Api:  
          Type: Api  
          Properties:  
            RestApiId: !Ref ApiGateway  
            Path: /ingest  
            Method: post  

  ProcessFunction:  
    Type: AWS::Serverless::Function  
    Properties:  
      Handler: app.process_data  
      Runtime: python3.8  
      Policies:  
        - DynamoDBCrudPolicy:  
            TableName: !Ref DataStore  
      Environment:  
        DATA_STORE: !Ref DataStore  
      Events:  
        SQSQueue:  
          Type: SQS  
          Properties:  
            Queue: !Ref DataProcessingQueue  

  DataStore:  
    Type: AWS::DynamoDB::Table  
    Properties:  
      TableName: ChildHealthData  
      AttributeDefinitions:  
        - AttributeName: id  
          AttributeType: S  
      KeySchema:  
        - AttributeName: id  
          KeyType: HASH  
      BillingMode: PAY_PER_REQUEST  

  DataProcessingQueue:  
    Type: AWS::SQS::Queue  

  NotificationTopic:  
    Type: AWS::SNS::Topic  

Outputs:  
  ApiUrl:  
    Description: "API Gateway URL"  
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
