name: CI/CD Pipeline  

on:  
  push:  
    branches:  
      - main  # Change to your desired branch  
  pull_request:  
    branches:  
      - main  # Change to your desired branch  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Check out code  
        uses: actions/checkout@v2  

      - name: Set up Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: '3.8'  

      - name: Install dependencies  
        run: |  
          cd child-health-data-platform  
          python -m pip install -r requirements.txt --target ./package  
          cd package && zip -r ../function.zip . && cd ..  
      
      - name: Package serverless application  
        run: |  
          sam package --output-template-file packaged.yaml --s3-bucket child-health-data-bucket  

      - name: Deploy serverless application  
        run: |  
          sam deploy --template-file packaged.yaml --stack-name child-health-data-platform --capabilities CAPABILITY_IAM  
        env:  
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          AWS_DEFAULT_REGION: eu-west-1
