name: CI/CD Pipeline  

on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - name: Check out code  
      uses: actions/checkout@v2  

    - name: Set up Python  
      uses: actions/setup-python@v2  
      with:  
        python-version: '3.8'  

    - name: Install dependencies  
      run: |  
        pip install -r requirements.txt  
        pip install pytest  

    - name: Run Tests  
      run: |  
        PYTHONPATH=./app pytest tests/  
    
  deploy:  
    runs-on: ubuntu-latest  
    needs: build  
    steps:  
    - name: AWS CLI  
      uses: aws-actions/configure-aws-credentials@v1  
      with:  
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
        aws-region: 'eu-west-1'  

    - name: Package SAM  
      run: |  
        sam package --template-file template.yaml --s3-bucket child-health-data-bucket --output-template-file output.yaml  

    - name: Deploy SAM  
      run: |  
        sam deploy --template-file output.yaml --stack-name child-health-data
