name: Deploy to AWS  

on:  
  push:  
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
        
      - name: Set up Python 3.8  
        uses: actions/setup-python@v2  
        with:  
          python-version: '3.8'  

      - name: Install dependencies  
        run: |  
          pip install awscli  
          pip install aws-sam-cli  
      
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1  
        with:  
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          aws-region: eu-west-1  

      - name: Build  
        run: |  
          sam build  

      - name: Deploy  
        run: |  
          sam deploy --stack-name HealthDataStack --capabilities CAPABILITY_IAM # Removed --guided
